// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Fri Sep 10 14:38:10 2021

ALU ALU_inst
(
	.r1(r1_sig) ,	// input [15:0] r1_sig
	.r2(r2_sig) ,	// input [15:0] r2_sig
	.rout(rout_sig) ,	// output [15:0] rout_sig
	.opcode(opcode_sig) 	// input [7:0] opcode_sig
);

